### ISSUE TITLE
Add SELinux status detection [BUG]

### ISSUE THREAD

**Issue by eschek87** [tribe29/ansible-collection-tribe29.checkmk#105]
**Describe the bug**
If selinux is disabled the role "tribe29.checkmk.server" to install check_mk and create a site failed with:
```
"msg": "SELinux is disabled on this host."
```

**Component Name**
roles/server/tasks/RedHat.yml with task name:
```
- name: "Enable httpd can network connect selinux boolean."
```

**Expected behavior**

Role does not fail, when selinux is disabled. Task could be improved with
```
when: ansible_facts.selinux.status == 'enabled'
```

**Comment by robin-tribe29** [comment]
Thanks for reporting this @eschek87!
I will take a look at it within the next week.
But I want to encourage you to try and find a solution and open a PR here. :slightly_smiling_face:

**Comment by robin-tribe29** [comment]
I implemented your solution. Thanks again.
This issue will close, once the commit hits the `main` branch. You could use the `devel` in the meantime however.
