### ISSUE TITLE
[FEED] Add tags to the roles to allow for more flexible runs

### ISSUE THREAD

**Issue by diademiemi** [tribe29/ansible-collection-tribe29.checkmk#112]
I propose we add tags to all tasks in the roles from this collection.  
I've used this collection to deploy 9 Checkmk sites (and counting!) over the past 2 weeks! It works great, however in networks where network access is restricted, or blocked completely, these roles cease to function at all. I have had to resort to just commenting out sections of code and doing the failed tasks manually.  

It would be great to skip tasks like downloading packages. The role does so much, which while configurable, still isn't very flexible. The roles still have a lot of function that might not be desired in a specific run. Of course it would be possible to add more booleans, but I feel adding tags is the preferred way of doing this. The booleans we have now still make sense, since those are ones that you likely want to configure per-host. 

I've even used this role to bulk import existing hosts into a Checkmk site. Since we had an inventory of them already, I just ran the agent role with all the tasks except the host and discovery tasks commented out.   

Sometimes if the agent hosts can not reach the Checkmk server on the HTTP port this will result in it completely failing. If we were to add tags to all tasks that download files, these files could still be sent to the servers in other means (Like `pre_tasks` in the playbook).  

Of course, editing the code before running it isn't a very good solution to this. Giving every task a tag would allow specific tasks to be skipped with `--skip-tags` or only certain tasks to be ran with `--tags` (or given in the playbook). 

If this is a wanted I can create a PR for this. 

If so, would we want tasks to have a prefix or not? eg. `checkmk_server_download` or just `download`? If you have a complicated playbook with multiple roles, you should be passing this along per role anyway, so I think just `download` would be fine and looks cleaner and less cluttered.

**Comment by robin-tribe29** [comment]
I like the idea overall because I can see the use cases quite clearly.
I also agree, that blindly adding more booleans does not make sense at this point.
As I have seen your work, I am positive that a PR will be of a quality, which we can easily merge. However, it might become a discussion which way to got, but that will be fine.
Regarding the tags I would keep it simple, as you suggested.

Looking forward to your PR!

**Comment by diademiemi** [comment]
Alright awesome, will start working on a PR now

**Comment by robin-tribe29** [comment]
Suggestion implemented in 4e47860cd5555cf7ebd685321a14929e6d77e1ce.
