### ISSUE TITLE
[FEED] Feature-Request: Allow to set/remove downtime

### ISSUE THREAD

**Issue by kasimon** [tribe29/ansible-collection-tribe29.checkmk#19]
**Provide your feedback**
Having the ability to set/clear downtimes for servers and/or services would make a lot of sense, for example as part of a update+reboot workflow.

**Comment by robin-tribe29** [comment]
A lot of work already went into this feature, thanks to @ogaida and @lgetwan! :tada:
Unfortunately we hit one more bump, that we need to resolve.
Keep an eye on the main branch and stay tuned for the next release. :slightly_smiling_face:

**Comment by robin-tribe29** [comment]
The release containing the brand-new downtime module just hit the [Galaxy](https://galaxy.ansible.com/tribe29/checkmk)! :tada:
