### ISSUE TITLE
[FEED] Ability to configure services programmatically

### ISSUE THREAD

**Issue by artiommocrenco** [tribe29/ansible-collection-tribe29.checkmk#191]
**Provide your feedback**
It would be good to have an option to configure checkmk services programmatically with an ansible module (within this collection), for example tribe29.checkmk.service.

Particularly, take this use case: https://checkmk.com/blog/how-to-monitor-web-server . It should be popular among checkmk users.

Company I work at manages hundreds of web virtual hosts and DNS entries.

Having the possibility to programmatically define at least simple checks (DNS, HTTP, TCP, etc.) would be helpful and more user-friendly than doing it manually. 

An alternative to using an ansible module would be implementing a terraform provider for this.  

**Component Name**
CheckMK

**Additional context**
Generally, we prefer solutions that can be fully **configured as a code** via terraform (or similar) and automation tools such as ansible. 

In our use case, we create the checkmk VPS with terraform, then use ansible to install and partially configure it.

Ideally, the checkmk VPS terraform resource can then be tainted, recreated, provisioned (in this case with ansible) and it would end up exactly the same as before the recreation (except the historical data). 

Unfortunately now it can not be fully configured with ansible because of lack of necessary modules, which compromises our configuration as code approach to everything and makes it necessary to implement custom solutions, rely on backups for actual hosts and services instead of having these immutably configured as code.

**Comment by robin-tribe29** [comment]
Hi @artiommocrenco and thank you for your feedback!

What you are looking for is the [rule module](https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/plugins/modules/rule.py). With it, you configure all rules within Checkmk, be it an additional HTTP service, or a disabled service or something entirely different.

A quick note towards terraform: I personally deem Terraform to be an infrastructure tool that spins up the infrastructure, while Ansible takes care of all configuration within the OS. That is only my personal take in a very abbreviated form, but for now we are not looking into developing a Terraform provider.
