### ISSUE TITLE
[FEED] rule module needs position parameter

### ISSUE THREAD

**Issue by geof77** [tribe29/ansible-collection-tribe29.checkmk#209]
We need a way to specify the position of the rules we create, otherwise they're created at the bottom of the list. 

I've coded this for my own needs and created a pull request.

My use case was to create service discovery rules before the generic, built-in, two-hours rule.

I've added two functions to rules.py

* get_rule_etag : gets the rule ETag needed for the next operation.
* move_rule: move the rule to the specified location as defined in the API documentation

I also added a new parameter I've called "position", it's a dict with the position and a rule_id (only for moves that need it: before_specific_rule and after_specific_rule).

Please review the PR. Suggestions/requests are welcome.

**Comment by robin-tribe29** [comment]
Hi @geof77 and thanks a lot for your contribution!
Can you add the information here into the pull request #208? You do not need an additional issue, we can do all the documentation and discussion in the pull request. :v:
