### ISSUE TITLE
[FEED] Create Use-Case Playbooks

### ISSUE THREAD

**Issue by robin-tribe29** [tribe29/ansible-collection-tribe29.checkmk#215]
Please verify first that your feedback is not already reported [here](https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues?q=is%3Aissue+sort%3Aupdated-desc).
If possible and useful provide additional information below. This is optional however.

**Provide your feedback**

Users of this collection might not be too seasoned with Ansible.
Under that assumption, it might make sense to provide playbooks for users, to get them started on specific use cases.

**This issue is a call for action!**

If you have a specific use case, that is not too specific to your environment and that you are willing to share, please open a pull request linking this issue!

**Component Name**

`playbooks`

**Ansible Version**

```console
$ ansible --version

```

**Collection Version**

```console
$ ansible-galaxy collection list

```
**Environment**

**Screenshots**

**Additional context**

Ideas:
- [x] Registration of hosts against a remote site (done in 5dd14f80b385b096fb87987dda5efb1930862211, updated in f2042261dfafd9fef5f05551bca6353654e30136)
- [ ] Local download of agent instead of direct download

**Comment by geof77** [comment]
Hi @robin-tribe29 
I'm currently writing a playbook (might end up being a role) to deploy and configure RobotMK. Would it fit?
I might need help or ideas on how to make it cooperate with the agent and server roles, which I don't currently use because I'm using CEE features (bakery, automatic updates,...)

**Comment by robin-tribe29** [comment]
@geof77 I am uncertain if that is too advanced, but I would hate to not even look at it. So I would gladly take a look, once you have something you want to show. Would you open an issue for this discussion, or a PR? Then we talk specifics there, without cluttering this thread. :)
