### ISSUE TITLE
[BUG] CCE not handled correctly in agent role

### ISSUE THREAD

**Issue by jherbel** [tribe29/ansible-collection-tribe29.checkmk#278]
**Describe the bug**
The agent role does not handle the CCE correctly, due to some conditions where handling `cce` as edition is missing.

**Component Name**

`tribe29.checkmk.agent`

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/joerg/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/joerg/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ansible
  ansible collection location = /home/joerg/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/joerg/.pyenv/versions/3.11.1/bin/ansible
  python version = 3.11.1 (main, Jan 20 2023, 16:32:15) [GCC 11.3.0] (/home/joerg/.pyenv/versions/3.11.1/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version**

```console
2.2.0 daily builds (CCE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection        Version
----------------- -------
amazon.aws        5.2.0  
ansible.posix     1.5.1  
community.general 6.3.0  
tribe29.checkmk   0.17.1
```
**Environment**
Ubuntu 22.04, Python 3.11

**To Reproduce**
Set `checkmk_agent_edition = "cce"` when deploying `tribe29.checkmk.agent` on a host. Of course, the Checkmk server must be a CCE.

**Expected behavior**
Agent is installed if the Checkmk server edition is CCE, error otherwise.

**Actual behavior**
No agent installed, even if the Checkmk server edition is CCE.

**Comment by robin-tribe29** [comment]
Fixed in `0.18.0`: #280.
