### ISSUE TITLE
[BUG] The role agent still uses automation_xxx variables instead of checkmk_agent_xxx

### ISSUE THREAD

**Issue by bartowl** [tribe29/ansible-collection-tribe29.checkmk#80]
**Describe the bug**
The agent role mentions ``checkmk_agent_user`` and ``checkmk_agent_pass`` in ``README`` and ``defaults/main.yml``,
but everywhere in code are still references to ``automation_user`` and ``automation_secret``. If those 2 are not passed from outside, role reports error. The mentioned variables are not used anywhere outside ``defaults.yml`` which seems to be a bug.

**Component Name**
agent role for sure, server role not checked

**Ansible Version**
all versions

**Checkmk Version**
all versions

**Collection Version**
v0.5.0

**Environment**
not relevant

**To Reproduce**
Just include the role without specifying ``automation_user`` and ``automation_secret`` variables, but providing ``checkmk_agent_user`` and ``checkmk_agent_pass``

**Expected behavior**
role uses checkmk_agent_* variables

**Actual behavior**
role uses automation_* variables

**Screenshots**

**Additional context**

**Comment by robin-tribe29** [comment]
Wow, that should have been an obvious catch. Thanks for noticing!
I am on the road for some days but will fix it afterwards. 

If someone wants to give it a try, go ahead!

**Comment by bartowl** [comment]
Thanks!

**Comment by robin-tribe29** [comment]
Let me know if you feel like there is a better approach than mine.
Preferably as a pull request. :slightly_smiling_face:
