### ISSUE TITLE
[FEED] Use variable name in agent registration

### ISSUE THREAD

**Issue by iscsrwm** [tribe29/ansible-collection-tribe29.checkmk#92]
Please verify first that your feedback is not already reported [here](https://github.com/tribe29/ansible-collection-tribe29.checkmk/issues?q=is%3Aissue+sort%3Aupdated-desc).
If possible and useful provide additional information below. This is optional however.

**Provide your feedback**
Use the checkmk_agent_host_name variable when registering agents in the agent role rather than inventory_hostname.  This would allow users to override the variable i.e. inventory_hostname_short 

**Component Name**
agent role registration

**Ansible Version**

```ansible [core 2.12.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

**Collection Version**

```tribe29.checkmk 0.4.0
```
**Environment**

**Screenshots**

**Additional context**

**Comment by robin-tribe29** [comment]
Thanks for your feedback!
I will look into this.
