### ISSUE TITLE
[BUG] failed_when test in Create host on server

### ISSUE THREAD

**Issue by iscsrwm** [tribe29/ansible-collection-tribe29.checkmk#94]
When adding the host to server the following error occurs:

`fatal: [ph-5qhfc42 -> localhost]: FAILED! => {"changed": true, "failed_when_result": "The conditional check 'checkmk_agent_create_result.failed is true and \"The host is already part of the specified target folder\" not in checkmk_agent_create_result.msg' failed. The error was: template error while templating string: no test named 'true'. String: {% if checkmk_agent_create_result.failed is true and \"The host is already part of the specified target folder\" not in checkmk_agent_create_result.msg %} True {% else %} False {% endif %}", "msg": "Host created."}`

The line of code in the role is this:

`failed_when: checkmk_agent_create_result.failed is true and "The host is already part of the specified target folder" not in checkmk_agent_create_result.msg`

I believe that should just be:

`failed_when: checkmk_agent_create_result.failed and "The host is already part of the specified target folder" not in checkmk_agent_create_result.msg`

**Component Name**
Agent Role - Create host on server

**Ansible Version**
```ansible [core 2.12.7]
  config file = /home/xxx/repos/ansible-collection-tribe29.checkmk/ansible.cfg
  configured module search path = ['/home/xxx/repos/ansible-collection-tribe29.checkmk/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

```

**Checkmk Version**
2.1.0p8

**Collection Version**
devel 

**Environment**

**To Reproduce**
Set:
checkmk_agent_add_host: 'true'

**Expected behavior**
Add host to server without erroring out.

**Actual behavior**
Errors out with the following error:
`fatal: [ph-5qhfc42 -> localhost]: FAILED! => {"changed": true, "failed_when_result": "The conditional check 'checkmk_agent_create_result.failed is true and \"The host is already part of the specified target folder\" not in checkmk_agent_create_result.msg' failed. The error was: template error while templating string: no test named 'true'. String: {% if checkmk_agent_create_result.failed is true and \"The host is already part of the specified target folder\" not in checkmk_agent_create_result.msg %} True {% else %} False {% endif %}", "msg": "Host created."}`

**Comment by robin-tribe29** [comment]
Hi @iscsrwm and thanks for the report.
I cannot reproduce the issue and your proposed solution is equivalent to the current implementation.
Can you provide a minimal reproduction example, so I can understand how the error comes about for you?

**Comment by iscsrwm** [comment]
It also runs fine when I kick it off via Rundeck in a container.  So maybe this is an issue with Ansible 2.12.7 on Ubuntu 20.04.  Anyhow I'll close this for now.

**Comment by robin-tribe29** [comment]
Thanks for the diagnosis @iscsrwm!
We had other issues with particular Ansible versions in the past, but our tests should have picked this one up.
I am quite restricted on time these days, if I can make some time, I will investigate a little more and see, if I can reproduce the issue.
But if I got you right, it works for you now?

**Comment by iscsrwm** [comment]
Yes, it's working.
